### ISSUE TITLE
publish should be atomic

### ISSUE THREAD

**Issue by thoward27** [relekang/python-semantic-release#189]
When running `semantic-release publish`, it pushes the new commit / tag even if the distribution fails. I believe the entire `publish` command should only make changes to git if the package actually gets published. Any thoughts on this one?

**Comment by relekang** [comment]
This is a difficult one. It can't be atomic since we cannot roll everything back automatically.  

There are a two possible ways:
* Push first (current implementation), if publish fails we have already pushed and cannot roll back automatically since it requires force push. With this we can retry upload to pypi to fix it.

* Publish first, if push fails we cannot roll back automatically or manually. If something was pushed in the meantime the only way to fix is to force push and overwrite.

I don't think the other option is better. Is there anything I am missing?
