### ISSUE TITLE
Version bump tries to bump all matching of `version =` in pyproject.toml

### ISSUE THREAD

**Issue by mbelang** [relekang/python-semantic-release#275]
## The problem

With version 7.3.0:

In pyproject.toml, the version of the main package is defined as `version = 1.2.3` but some dependencies can be defined as such `pyarrow = {version = "0.17.0", extras = [ "pandas" ] }` and then semantic release is either bumping both `version = ` the the computed version or trowing an error such as:

```
semantic-release version --patch
Creating new version
error: found conflicting versions: '1.2.3', '0.17.0'
```

## Expected behavior

semantic release only bump the root version of the package and nothing in the dependencies section.

## Additional context

Here is an example of pyproject.toml that you can use to reproduce
```
[tool.poetry]
name = "potatoes"
version = "1.2.3"
description = "I love potatoes"
authors = ["Potatoes <potatoes@potatoes.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pyarrow = {version = "0.17.0", extras = [ "pandas" ] }

[tool.semantic_release]
version_variable = "pyproject.toml:version"
upload_to_pypi = false
commit_message = "Version generated by python-semantic-release [ci skip]"
```

**Comment by danth** [comment]
I suggest we change the regular expression for `version_variable` to only match at the start of a line:

https://github.com/relekang/python-semantic-release/blob/da20b9bdd3c7c87809c25ccb2a5993a7ea209a22/semantic_release/history/__init__.py#L41-L49

**Comment by Cielquan** [comment]
As I am currently looking at different tools for the best to fit my automatic release pipeline plans I came across [`standard-version`](https://github.com/conventional-changelog/standard-version). It's a tool written in JS which does almost the same as `python-semantic-versioning` except it does not build and publish the package.

As I wanted to try to use it for python projects I had to write a custom updater for bumping the version in `pyproject.toml`. First I tried to find a JS toml lib which could parse and dump. I came across `iarna-toml` which was the only lib I found which could dump. Problem with this lib was that the dump was very different from my original. All comments were gone, my custom indentation was gone and the structure was changed significantly.

E.g. this line:
```toml
pylint = {version = "^2.5.3", optional = true}
```
was written as:
```toml
[tool.poetry.dependencies.pylint]
version = "^2.5.3"
optional = true
```
which let to an increase of 120 line in my `pyproject.toml` (currently around 350 lines) even with comments removed.

**My point is that the toml lib one chooses needs to be chosen carefully.**

I mentioned `tomlkit` prior because `poetry` uses it and I adopted it too. I made a quick test with the load/dump thing and it worked perfectly as everything was preserved. Here is an example for the python code (`bump_version()` is a fictional function):
```python
import tomlkit

with open("pyproject.toml") as pyproject_file:
    pyproject = tomlkit.parse(pyproject_file.read())

current_version = pyproject["tool"]["poetry"]["version"]
new_version = bump_version(current_version)
pyproject["tool"]["poetry"]["version"] = new_version

with open("pyproject.toml", "w") as pyproject_file:
    pyproject_file.write(tomlkit.dumps(pyproject))
```
