### ISSUE TITLE
build_command can not be set to False

### ISSUE THREAD

**Issue by aNebula** [relekang/python-semantic-release#328]
## The problem

Setting `build_command` to `False` is not working. 
I already have a `/dist` folder which I want to keep. I also don't want to push to pypi.
Seems like `semantic-release release` trying to run the command `false`.

## Expected behavior
Setting `build_command` to `False` should disable build.

## Additional context
setup.cfg
```
[semantic_release]
branch = main
build_command=false
upload_to_pypi=false
remove_dist=false
version_pattern =catalogs/mycatalog/catalog/metadata.json:\"version\": "(\d+\.\d+\.\d+)"
```

logs
```
Bumping with a major version to 9.0.0
Pushing new version
Building distributions
Running false
error: Encountered a bad command exit code!
error: 
error: Command: 'false'
error: 
error: Exit code: 1
```

**Comment by danth** [comment]
Setting `build_command` to an empty string should disable building. You could alternatively set `upload_to_release` to false.

https://github.com/relekang/python-semantic-release/blob/c07a440f2dfc45a2ad8f7c454aaac180c4651f70/semantic_release/dist.py#L12-L16

The bug here is that `should_build()` checks for a falsy value, but the string `"false"` is actually truthy.
