### ISSUE TITLE
GitLab: Error because of deprecated method

### ISSUE THREAD

**Issue by FirstSanny** [relekang/python-semantic-release#350]
## The problem
![grafik](https://user-images.githubusercontent.com/23708333/121675783-26465680-cab4-11eb-8197-800a1c8ebd76.png)
As you can see here, the script tries to call an deprecated method and that threq an error in my pipeline.

`error: Release notes modification via tags API is deprecated, see https://gitlab.com/gitlab-org/gitlab/-/issues/290311: 400`

## Expected behavior
Since the method is deprecated dont update the release tag at all, i guess?

**Comment by matteosantama** [comment]
@FirstSanny What version of `python-semantic-release` are you using?

**Comment by nejch** [comment]
You just need to make sure to call the Releases API (https://python-gitlab.readthedocs.io/en/stable/gl_objects/releases.html in python-gitlab) rather than use the Create Release of the Tags API which will be removed in a few weeks in Gitlab 14.0 (it's not even in the docs on gitlab.com anymore).

We use python-semantic-release for python-gitlab :) so I'd be happy to open a small PR for this as well.

**Comment by FirstSanny** [comment]
> 
> 
> @FirstSanny What version of `python-semantic-release` are you using?

Used version 7.16.1.
