### ISSUE TITLE
changelog command never outputs anything

### ISSUE THREAD

**Issue by vigenere23** [relekang/python-semantic-release#483]
## The problem

Whenever I run the command `changelog`, nothing is ever outputed. Be it having the file not empty, having a pending version change or a newly changed version, after publishing, etc.

## Expected behavior

I'm not sure... what is the command even supposed to do? I excpect it to append an entry to the changelog file, if there is none yet for the current version. Aka I expect the `publish` command to be a combination of `version`, `changelog` and pushing the commit/tag everywhere (git, pypi, etc.).

**Comment by Jalkhov** [comment]
Same here, i run `semantic-release -v DEBUG changelog` but there is nothing usefull in the output.

**Comment by codejedi365** [comment]
What is your `version_source` set to? If you are using `tag`, there is already a known bug and fix in the works where changelog is empty (see #362, #171, #486).  Currently, if you are using the default `version_source = 'commit'` then it requires a commit with the version number in the subject line to be detect where to start and stop the gathering of commits for the changelog.

As for the debug log, if you see the line at the end where it returns an empty array, that is why there is no changelog. No commits were found to be used (this is because of the logic error previously described).

**Comment by Jalkhov** [comment]
Yes, I just found that issue, as you say I changed `version_source = 'commit'` and all fixed.

**Comment by vigenere23** [comment]
For me it seems to now output a random older commit... However, when publishing, the changelog is fine.

**Comment by codejedi365** [comment]
@vigenere23 , I think you need to add more specifics or close the issue if it is resolved. If you provide your config, the actions you take and what the debug output provides, and probably the commit history you are trying to create this might help debug your issue. But currently, I can't think what workflow give you a weird result.

**Comment by vigenere23** [comment]
There was a problem with the merge and the commit history was all crapped. This now seems to be fine, I will follow the other linked issues for more details or solutions if it ever happens again.
