### ISSUE TITLE
Add a "getting started" guide.

### ISSUE THREAD

**Issue by skorokithakis** [relekang/python-semantic-release#49]
I'm looking for something to help automate the release of various libraries I write, so something that would bump versions automatically, commit and push tags, generate changelog etc would be great, but I can't for the life of me figure out how to use this project. I've gleaned some information from the various documentation, but when I run `semantic-release version` it keeps telling me it won't make a new release.

A "getting started" guide with a few steps for how to try this tool out would be very nice.

**Comment by relekang** [comment]
Good idea, I'll try to review the docs this weekend. I thought there were something, but I must have forgot it.

The key is the commit messages since last release. If you use the default parser it looks for [angular commit style](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit) where commits with the type `feat` or `fix` will create releases, in addition a commit with `BREAKING CHANGE` in the footer would also create a release. To know which commits to include it uses the git log since the tag of the latest release. That means if the version in the version variable is `1.0.0` then it would evaluate the commits in `git log v1.0.0...`.

Make sure these things is correct:
* Last version is tagged with a tag that has the current version number prefixed with `v`.
* There are some commit since then that will be evaluated to trigger a new version.
* [version_variable](http://python-semantic-release.readthedocs.org/en/latest/configuration.html) is set in setup.cfg

**Comment by skorokithakis** [comment]
Thank you, that's pretty much all that's needed. It looks like I only had `chore`-type commits, that's why a release wasn't created. By the way, you have an error in documentation, you mention that the `setup.cfg` header should be `semantic-release` and it's `semantic_release`.

Thank you!

**Comment by relekang** [comment]
Sweet :sparkles: 

The typo should be fixed now, thanks for mentioning it.

**Comment by slhck** [comment]
Any updates on this? I have troubles getting started with this tool on a new project, since whatever command I run, I get errors.

I would like some basic instructions like:

- Do I **need** to specify the version variable reference in a `pyproject.toml`? Or will it create a separate file to store the version by default? I would have expected the latter, but if I have to put it in a Python file, that's fine.

- What tags need to exist? Do I have to have a `v0.0.1` tag to begin with?

Perhaps this can be added to the README.

Thanks!

**Comment by relekang** [comment]
The variable should be in a python file and referenced in either `pyproject.toml` and `setup.cfg`. If it complains about missing tag it is possible to force a release by passing the bump level flag.

**Comment by slhck** [comment]
Thanks!

I believe though that all these points should be part of the README, or directly caught by the command with a helpful error message. Right now it’s hard to get started with the project.

**Comment by relekang** [comment]
I agree, PRs are very much welcome.

**Comment by Sieboldianus** [comment]
> The variable should be in a python file and referenced in either `pyproject.toml` and `setup.cfg`. If it complains about missing tag it is possible to force a release by passing the bump level flag.

Just an add: it doesn't have to be. We tested and used `.version` (with __version__ = 'v1.0.0' as content) and it also works. This looks less interrupting if working in non-python repositories.

**Comment by slhck** [comment]
Hm. I guess I still don't even slightly understand how this tool works and hence am unable to provide a PR.

**Comment by relekang** [comment]
@slhck I updated the readme hope it helps. If not please re-open the issue and add some notes about what is hard to understand or where you are stuck.
