### ISSUE TITLE
Support of parser_angular_* config options

### ISSUE THREAD

**Issue by vagenas** [relekang/python-semantic-release#499]
When using the default commit parser (Angular), the text patterns used for triggering the minor and patch version bumping are currently configured via config options `parser_angular_minor_types` and `parser_angular_patch_types` accordingly:
https://github.com/relekang/python-semantic-release/blob/ffae2dc68f7f4bc13c5fd015acd43b457e568ada/semantic_release/history/parser_angular.py#L39-L40

We would like to add these options to our `pyproject.toml`, but as we have not been able to find any documentation on them, we are wondering if they are indeed meant as a part of your public API (i.e. you plan to maintain/support them, they are just not documented yet), or are rather an implementation detail that can change at any time.

By convention, undocumented probably means unsupported, but these options would come in very handy when it comes to configuring parsing, so it would be great if they are indeed meant for users.

**Comment by bernardcooke53** [comment]
Hey @vagenas
I can't give you a definitive answer since I'm not a maintainer, but these options have been present since [this commit](https://github.com/relekang/python-semantic-release/commit/bf21fa6ccf9cf8327493821ae01f98caaf32c890) which was released in v7.22.0. They aren't documented but were added as an explicit feature so I'd expect you're fine to use them as removing them should trigger a v8 (and equally v8 may contain an alternative - I'm looking at standardising these options with the other parsers as part of some work I'm doing at the moment).
